/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DB.ConnectSqlite;
import Data.Cartera;
import Data.Opcion;
import ServerAccess.MEFF_Opciones;
import java.util.ArrayList;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lala
 */
public class Cartera_table extends javax.swing.JPanel {

    private Cartera wallet;
    private final JTabbedPane parent;

    /**
     * Creates new form Cartera_table
     */
    public Cartera_table(String name, JTabbedPane p) {
        this.wallet = new Cartera(name);
        ConnectSqlite connection = new ConnectSqlite();
        fillWallet(connection);
        connection.desconectar();
        initComponents();
        cleanTable();
        updateTable();
        updateGeneralInformation();
        this.parent = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new ViewExtentions.HighLightPassedDates();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        generalPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        investmentTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        gainTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        walletValueTextField = new javax.swing.JTextField();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cantidad", "Tipo", "Vencimiento", "Ejercicio", "Fecha de Compra", "Precio de Compra", "Precio de Venta", "Ganancia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(table);

        jButton1.setText("Refrescar opciones.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar opciones seleccionadas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cerrar cartera");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        generalPanel.setBackground(new java.awt.Color(255, 255, 255));
        generalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Información General"));

        jLabel1.setText("Inversión total en esta cartera:");

        investmentTextField.setEditable(false);

        jLabel2.setText("Ganancias en el conjunto de todas las opciones:");

        gainTextField.setEditable(false);
        gainTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gainTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Valoración de todas las opciones de la cartera:");

        walletValueTextField.setEditable(false);

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1))
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(investmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(gainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(walletValueTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walletValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(investmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 531, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addGap(25, 25, 25)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       refreshWallet();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int[] selection = table.getSelectedRows();
        ConnectSqlite conn = new ConnectSqlite();
        
        for (int i = selection.length-1; i >= 0; i--) {
            conn.removeOptionFromWallet(wallet.getId(), wallet.getOpciones().get(selection[i]));
            wallet.removeOptionInIndex(selection[i]);
        }
        conn.desconectar();
        refreshWallet();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       parent.remove(parent.getSelectedIndex());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void gainTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gainTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gainTextFieldActionPerformed

    
    private void refreshWallet(){
        ConnectSqlite connection = new ConnectSqlite();
        String name = this.wallet.getId();
        this.wallet = new Cartera(name);
        fillWallet(connection);
        connection.desconectar();
        cleanTable();
        updateTable();
        updateGeneralInformation();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gainTextField;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JTextField investmentTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField walletValueTextField;
    // End of variables declaration//GEN-END:variables

    private void updateTable() {

        DefaultTableModel tableData = (DefaultTableModel) table.getModel();

        for (Opcion opt : wallet.getOpciones()) {
            Opcion opcion = obtainFields(opt);
            tableData.addRow(opcion.showWallet());
        }
        
    }

    private void fillWallet(ConnectSqlite connection) {
       ArrayList<Opcion> options =  connection.selectOptionsFromWallet(this.wallet.getId());
        for (Opcion option : options) {
            wallet.addOpcion(option);
        }
    }

    private void cleanTable() {
        DefaultTableModel tableData = (DefaultTableModel) table.getModel();
        int rows = tableData.getRowCount();
        for (int i = (rows - 1); i >= 0; i--) {
            tableData.removeRow(i);
        }
    }
    private Opcion obtainFields(Opcion opt){
        if(opt.Tipo.equals("PUT")){
            for(Opcion option: Put_options.getPut_options()){
                if(opt.Ejercicio.equals(option.Ejercicio) && opt.Vencimiento.equals(option.Vencimiento)){
                    opt.Precio_Vender = option.Compra_Precio;
                    if(!opt.Precio_Vender.contains("-") && !opt.Venta_Precio.contains("-")){
                        double ganancia =  Double.parseDouble(opt.Precio_Vender.replace(",",".")) -Double.parseDouble(opt.Venta_Precio.replace(",", "."));
                        String Ganancia = String.valueOf(ganancia);
                        opt.Ganancia = Ganancia.replace(".",",");
                    }else{
                        opt.Ganancia = "0";
                    }
                }
            }
        }else{
            for(Opcion option: Call_options.getCall_options()){
                if(opt.Ejercicio.equals(option.Ejercicio) && opt.Vencimiento.equals(option.Vencimiento)){
                    opt.Precio_Vender = option.Compra_Precio; 
                    if(!opt.Precio_Vender.contains("-") && !opt.Venta_Precio.contains("-")){
                        double ganancia =  Double.parseDouble(opt.Precio_Vender.replace(",",".")) -Double.parseDouble(opt.Venta_Precio.replace(",", "."));
                        String Ganancia = String.valueOf(ganancia);
                        opt.Ganancia = Ganancia.replace(".",",");
                    }else{
                        opt.Ganancia = "0";
                    }
                }
            }
        }
        return opt;
    }

    private void updateGeneralInformation() {
        Double totalGain = getTotalGain();
        gainTextField.setText(totalGain.toString());
        Double investment = getTotalInvestment();
        investmentTextField.setText(investment.toString());
        Double value = getTotalValue();
        walletValueTextField.setText(value.toString());
    }

    private double getTotalGain() {
        double result = 0;
        for (Opcion opt : wallet.getOpciones()) {
            if(opt.Ganancia == null || opt.Cantidad == null){
                result +=0;
                continue;
            }
            result += Double.parseDouble(opt.Ganancia.replace(",", "."))* Double.parseDouble(opt.Cantidad.replace(",", "."));
        }
        return result;
    }

    private double getTotalInvestment() {
        double result = 0;
        for (Opcion opt : wallet.getOpciones()) {
            if(opt.Venta_Precio == null || opt.Cantidad == null){
                result +=0;
                continue;
            }
            result += Double.parseDouble(opt.Venta_Precio.replace(",", ".")) * Double.parseDouble(opt.Cantidad.replace(",", "."));
        }
        return result;
    }

    private Double getTotalValue() {
        double result = 0;
        for (Opcion opt : wallet.getOpciones()) {
            if(opt.Precio_Vender == null || opt.Cantidad == null || opt.Precio_Vender.contains("-")){
                result +=0;
                continue;
            }
            result += Double.parseDouble(opt.Precio_Vender.replace(",","."))* Double.parseDouble(opt.Cantidad.replace(",", "."));
        }
        return result;
    }
    
    
}
