package View;

import DB.ConnectSqlite;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author lala
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        LoadingDialog dia = new LoadingDialog(this, false, 3);
        dia.setVisible(true);
        initDefaultTables(dia);
        changeTabbedPaneLook();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public void initDefaultTables(LoadingDialog dia) {
        TableTabbedPane.add("Futuros", new Futuros_table());
        dia.taskComplete();
        TableTabbedPane.add("Opciones CALL", new Call_options());
        dia.taskComplete();
        TableTabbedPane.add("Opciones PUT", new Put_options());
        dia.taskComplete();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoDialog = new javax.swing.JDialog();
        infoIcon = new javax.swing.JLabel();
        infoHeader = new javax.swing.JLabel();
        subtitleHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoField = new javax.swing.JTextArea();
        developerCredit = new javax.swing.JLabel();
        webSiteCredit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hideInfoDialogButton = new javax.swing.JButton();
        manageDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        availableCarterasList = new javax.swing.JList();
        createNewCartera = new javax.swing.JButton();
        removeCartera = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        createWalletDialog = new javax.swing.JDialog();
        addWalletTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addWallet = new javax.swing.JButton();
        showSelectionDialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        availableWalletList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        showSelectionButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        conectionStatusPane1 = new View.ConectionStatusPane();
        TableTabbedPane = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        menuBarFileSpot = new javax.swing.JMenu();
        connectButton = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        manageCarteras = new javax.swing.JMenuItem();

        infoDialog.setTitle("Sobre MoMiMeef");
        infoDialog.setModal(true);
        infoDialog.setResizable(false);

        infoIcon.setText("Icon");

        infoHeader.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        infoHeader.setText("MoMiMeef");

        subtitleHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitleHeader.setText("Monitoring MiniIbex desde Meef");

        infoField.setEditable(false);
        infoField.setColumns(20);
        infoField.setLineWrap(true);
        infoField.setRows(5);
        infoField.setText("MoMiMeef es una herramienta para la monitorización de las opciones y \nfuturos del MiniIbex35 que toma su información directamente de la página del MEEF.");
        jScrollPane1.setViewportView(infoField);

        developerCredit.setText("Desarrollador: Aitor Saavedra Hernández & Laura del Pino Díaz.");

        webSiteCredit.setText("Web: https://github.com/LauraLaureus/MoMiMeef");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel2.setText("Desarrollado para la asignatura de Diseño de Interfaces de Usuario -EII-ULPGC");

        hideInfoDialogButton.setText("Ocultar");
        hideInfoDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideInfoDialogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoDialogLayout = new javax.swing.GroupLayout(infoDialog.getContentPane());
        infoDialog.getContentPane().setLayout(infoDialogLayout);
        infoDialogLayout.setHorizontalGroup(
            infoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoDialogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(infoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(infoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(webSiteCredit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(developerCredit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(infoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(infoDialogLayout.createSequentialGroup()
                            .addGap(300, 300, 300)
                            .addComponent(infoHeader))
                        .addGroup(infoDialogLayout.createSequentialGroup()
                            .addComponent(infoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(infoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(infoDialogLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subtitleHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(infoDialogLayout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hideInfoDialogButton)
                .addGap(15, 15, 15))
        );
        infoDialogLayout.setVerticalGroup(
            infoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoDialogLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(infoHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoDialogLayout.createSequentialGroup()
                        .addComponent(subtitleHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoDialogLayout.createSequentialGroup()
                        .addComponent(infoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addComponent(developerCredit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webSiteCredit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(hideInfoDialogButton)
                .addContainerGap())
        );

        availableCarterasList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(availableCarterasList);

        createNewCartera.setText("Crear nueva cartera");
        createNewCartera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewCarteraActionPerformed(evt);
            }
        });

        removeCartera.setText("Eliminar cartera");
        removeCartera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCarteraActionPerformed(evt);
            }
        });

        jLabel1.setText("Carteras disponibles");

        jButton1.setText("Mostrar cartera seleccionada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageDialogLayout = new javax.swing.GroupLayout(manageDialog.getContentPane());
        manageDialog.getContentPane().setLayout(manageDialogLayout);
        manageDialogLayout.setHorizontalGroup(
            manageDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageDialogLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(manageDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(manageDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(manageDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createNewCartera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeCartera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageDialogLayout.setVerticalGroup(
            manageDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageDialogLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageDialogLayout.createSequentialGroup()
                        .addComponent(createNewCartera)
                        .addGap(13, 13, 13)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeCartera))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jLabel3.setText("Nombre de la nueva cartera");

        addWallet.setText("Aceptar");
        addWallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWalletActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createWalletDialogLayout = new javax.swing.GroupLayout(createWalletDialog.getContentPane());
        createWalletDialog.getContentPane().setLayout(createWalletDialogLayout);
        createWalletDialogLayout.setHorizontalGroup(
            createWalletDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createWalletDialogLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(createWalletDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createWalletDialogLayout.createSequentialGroup()
                        .addComponent(addWalletTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addWallet))
                    .addComponent(jLabel3))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        createWalletDialogLayout.setVerticalGroup(
            createWalletDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createWalletDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createWalletDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addWalletTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addWallet))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(availableWalletList);

        jLabel4.setText("Listas disponibles");

        showSelectionButton.setText("Mostrar seleccion");
        showSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSelectionButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showSelectionDialogLayout = new javax.swing.GroupLayout(showSelectionDialog.getContentPane());
        showSelectionDialog.getContentPane().setLayout(showSelectionDialogLayout);
        showSelectionDialogLayout.setHorizontalGroup(
            showSelectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showSelectionDialogLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(showSelectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(showSelectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(showSelectionDialogLayout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(showSelectionButton))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        showSelectionDialogLayout.setVerticalGroup(
            showSelectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showSelectionDialogLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(showSelectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showSelectionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MoMiMeef");
        setIconImage(new javax.swing.ImageIcon("logo.png").getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        menuBarFileSpot.setText("General");

        connectButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        connectButton.setText("Conectar ahora");
        menuBarFileSpot.add(connectButton);

        aboutMenuItem.setText("Sobre MoMiMeef");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        menuBarFileSpot.add(aboutMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        menuBarFileSpot.add(exitMenuItem);

        menuBar.add(menuBarFileSpot);

        jMenu1.setText("Carteras");

        manageCarteras.setText("Gestionar Carteras");
        manageCarteras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCarterasActionPerformed(evt);
            }
        });
        jMenu1.add(manageCarteras);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TableTabbedPane)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(691, Short.MAX_VALUE)
                .addComponent(conectionStatusPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(conectionStatusPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TableTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        confirmExit();
    }//GEN-LAST:event_formWindowClosing

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        confirmExit();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        showInfoDialog();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void hideInfoDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideInfoDialogButtonActionPerformed
        infoDialog.setVisible(false);
    }//GEN-LAST:event_hideInfoDialogButtonActionPerformed

    private void manageCarterasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCarterasActionPerformed
        updateWallet();
        manageDialog.pack();
        manageDialog.setVisible(true);
    }//GEN-LAST:event_manageCarterasActionPerformed

    private void addWalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWalletActionPerformed
        String name = addWalletTextField.getText();
        List<String> nameWallets = dbWallets.showAllWallets();
        name = name.trim();
        if (nameWallets.contains(name) || name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Esta cartera no puede ser creada", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            dbWallets.insertWallet("'" + name + "'");
            updateWallet();
            createWalletDialog.setVisible(false);
        }
    }//GEN-LAST:event_addWalletActionPerformed

    private void createNewCarteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewCarteraActionPerformed
        createWalletDialog.pack();
        createWalletDialog.setVisible(true);
    }//GEN-LAST:event_createNewCarteraActionPerformed

    private void showSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSelectionButtonActionPerformed
        List selection = availableWalletList.getSelectedValuesList();
        for (Object selection1 : selection) {
        }
    }//GEN-LAST:event_showSelectionButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tabName = availableCarterasList.getSelectedValue().toString();
        //TODO controlar que la cartera no esté abierta ya.
        for (int i = 0; i < TableTabbedPane.getTabCount(); i++) {
            if(TableTabbedPane.getTitleAt(i).equalsIgnoreCase(tabName)) return;
        }
        TableTabbedPane.addTab(tabName, new Cartera_table(tabName,TableTabbedPane));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void removeCarteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCarteraActionPerformed
        List l = availableCarterasList.getSelectedValuesList();
        for (Object element : l) {
            dbWallets.deleteWallet("'" + element.toString() + "'");
        }
        updateWallet();
    }//GEN-LAST:event_removeCarteraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        showSelectionDialog.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void confirmExit() {
        int returnable = JOptionPane.showConfirmDialog(this, "¿Está seguro de que quiere salir?", "Salir", JOptionPane.OK_CANCEL_OPTION);
        if (returnable == 0) {
            System.exit(0);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TableTabbedPane;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton addWallet;
    private javax.swing.JTextField addWalletTextField;
    private javax.swing.JList availableCarterasList;
    private javax.swing.JList availableWalletList;
    private View.ConectionStatusPane conectionStatusPane1;
    private javax.swing.JMenuItem connectButton;
    private javax.swing.JButton createNewCartera;
    private javax.swing.JDialog createWalletDialog;
    private javax.swing.JLabel developerCredit;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton hideInfoDialogButton;
    private javax.swing.JDialog infoDialog;
    private javax.swing.JTextArea infoField;
    private javax.swing.JLabel infoHeader;
    private javax.swing.JLabel infoIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem manageCarteras;
    private javax.swing.JDialog manageDialog;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBarFileSpot;
    private javax.swing.JButton removeCartera;
    private javax.swing.JButton showSelectionButton;
    private javax.swing.JDialog showSelectionDialog;
    private javax.swing.JLabel subtitleHeader;
    private javax.swing.JLabel webSiteCredit;
    // End of variables declaration//GEN-END:variables
    //private HashMap<String,Cartera> wallets;
    private ConnectSqlite dbWallets = new ConnectSqlite();

    private void showInfoDialog() {
        infoDialog.pack();
        infoDialog.setVisible(true);
    }

    private void changeTabbedPaneLook() {
        Color c = new Color(25, 248, 0);
        for (int i = 0; i < TableTabbedPane.getTabCount(); i++) {
            TableTabbedPane.setBackgroundAt(i, c);
            TableTabbedPane.setForegroundAt(i, Color.BLACK);
        }
    }

    private void loadCarteras() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    private void updateWallet() {
       
        List setWallets = dbWallets.showAllWallets();
        availableWalletList.setListData(setWallets.toArray());
        availableCarterasList.setListData(setWallets.toArray());
    }
}
